CREATE DATABASE IF NOT EXISTS orca_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'DEVALOPER'@'localhost' IDENTIFIED BY 'OrcaDb123';
GRANT ALL PRIVILEGES ON orca_db.* TO 'DEVALOPER'@'localhost';
FLUSH PRIVILEGES;


USE orca_db;